

%% Import data from text file.
% Script for importing data from the following text file:
%
%    G:\My Drive\BYU Prep\Research\2019-03-06, ConvNet\Bottom_small.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/03/06 09:28:20

%% Initialize variables.
filename = 'G:\My Drive\BYU Prep\Research\2019-03-06, ConvNet\Middle_small.txt';
delimiter = '\t';
startRow = 2;

%% Format for each line of text:
formatSpec = '%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Allocate imported array to column variable names
x = dataArray{:, 1};
y = dataArray{:, 2};
z = dataArray{:, 3};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;



%% From https://stackoverflow.com/questions/12614686/matlabmake-a-contour-plot-with-3-vectors

%Create regular grid across data space
nx = 108;
ny = 196;
[X,Y] = meshgrid(linspace(min(x),max(x),nx), linspace(min(y),max(y),ny));
Z = griddata(x,y,z,X,Y);

%create contour plot
figure;
contourf(X,Y,griddata(x,y,z,X,Y));
colorbar 
True_Temp = Z;
%%
% d_theta = 360/nr;
% theta  = [1:d_theta:360];

% [x,y] = pol2cart(theta,r);

%% 
T1 = 20+273-5; %Top and bottom temperatures (K)
T2 = 96+273-5; %Side Temperatures (K)

% This creates a linear relationship between the temperature and pixel
% values of an image, and assumes a 16 bit pixel depth so that smaller
% temperature variations can be seen (a lot of greyscale cameras are 12
% bit, but you can change the bit depther easily
bit = 16;   %number of bits per pixel
grey_max = 2^bit - 1;
grey_min = 0;
temp_max = T2;
temp_min = T1;

m = (grey_max-grey_min) / (temp_max-temp_min);
b = grey_min - (m*temp_min);

%Image intensity due to temperature
I = m * True_Temp + b;
Ired(:,:) = -287.74*True_Temp(:,:) + 144236;
Igreen(:,:) = -73.933*True_Temp(:,:) + 36096;
Iblue(:,:) = -11.272*True_Temp(:,:) + 4198;